# -*- coding: utf-8 -*-
{
    "name": "Rutas de entrega",
    "summary": "Modulo de rutas de entrega",
    "description": """Modulo de rutas de entrega""",
    "author": "DGV",
    "website": "https://github.com/AlfaSystemas5457/delivery_routes",
    "license": "LGPL-3",
    "category": "Warehouse Management",
    "version": "0.1",
    "depends": ["base", "stock", "hr", "sale", "mail", "web", "account"],
    "data": [
        "security/ir.model.access.csv",
        "security/groups_security.xml",
        "security/route_security.xml",
        "data/days_data.xml",
        "report/paperformat.xml",
        "report/report.xml",
        "report/report_delivery.xml",
        "report/report_invoice.xml",
        "report/cash_out_report.xml",
        "views/pos_view.xml",
        "views/view_picking.xml",
        "views/account_move_view.xml",
        "views/res_users_views.xml",
        "views/menu_views.xml",
        "views/delivery_config_views.xml",
        "views/route_sale_address_view.xml",
        "views/route_view.xml",
        "views/address_view.xml",
        "views/stock_picking_signature.xml",
        "views/res_partner_view.xml",
        "views/stock_report_delivery_document.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "delivery_routes/static/src/components/**/*.xml",
            "delivery_routes/static/src/components/**/*.js",
            "delivery_routes/static/src/components/**/*.scss",
            ("remove", "delivery_routes/static/src/components/**/*.dark.scss"),
            "https://cdn.jsdelivr.net/npm/signature_pad@4.0.0/dist/signature_pad.umd.min.js",
        ],
        "web.assets_web_dark": [
            "delivery_routes/static/src/components/**/*.dark.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
    "sequence": 0,
}
